### ISSUE TITLE
cnpm permission denied

### ISSUE THREAD

**Issue by fsckzy** [Gozap/dockerfile#1]
请问下这个怎么解决？

**Comment by mritd** [comment]
请问是那个镜像？

**Comment by fsckzy** [comment]
> 请问是那个镜像？

node的，我照着您的dockfile和shell脚本也制作了一个node，然后打包node代码进去的时候，就提示这个了。。
打包node代码使用的Dockerfile如下：
```yaml
FROM 172.18.11.161/lzwd/node:8.16.0-stretch-slim
LABEL maintainer="liyi01<liyi01@wondersgroup.com>"
ENV TZ=Asia/Shanghai
COPY . /app/
WORKDIR /app
RUN cnpm install
ARG port
EXPOSE $port
ENV NODE_ENV test
ENTRYPOINT ["/bin/sh","-c","npm $NODE_ENV"]
```

**Comment by fsckzy** [comment]
报错如下：
```shell
Step 5/9 : RUN /usr/local/bin/cnpm install
 ---> Running in 3d73cc9246b7
[91m/bin/sh: 1: /usr/local/bin/cnpm: Permission denied
[0mThe command '/bin/sh -c /usr/local/bin/cnpm install' returned a non-zero code: 126
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by mritd** [comment]
@fsckzy 如果想自行修改 node 镜像版本，你可以 使用 git clone 本仓库代码，然后只修改 Dockerfile 既可；你的错误原因应该是 `172.18.11.161/lzwd/node:8.16.0-stretch-slim` build 的时候，cnpm 这个脚本没有可执行权限导致的；一般这种情况出现在你手动 复制 cnpm 脚本或者手动编写的情况下造成的 cnpm 可执行权限丢失

**Comment by mritd** [comment]
建议在 纯 linux 下进行 修改，以及使用 git  clone 的方式复制代码确保相关可执行权限不会丢失

**Comment by fsckzy** [comment]
> @fsckzy 如果想自行修改 node 镜像版本，你可以 使用 git clone 本仓库代码，然后只修改 Dockerfile 既可；你的错误原因应该是 `172.18.11.161/lzwd/node:8.16.0-stretch-slim` build 的时候，cnpm 这个脚本没有可执行权限导致的；一般这种情况出现在你手动 复制 cnpm 脚本或者手动编写的情况下造成的 cnpm 可执行权限丢失

我用git clone下载源码发现原来 cnpm 没有x的权限，+x就可以了。多谢

**Comment by mritd** [comment]
![image](https://user-images.githubusercontent.com/13043245/59399131-773beb00-8dc5-11e9-9ba3-5f0d6161ae29.png)

不清楚你是什么时候 clone 的，但是目前 node 镜像的 最后提交 cnpm 是有可执行权限的 😀
