### ISSUE TITLE
之前那次帮我调试的jvm参数咋没了

### ISSUE THREAD

**Issue by zhangguanzhang** [Gozap/dockerfile#3]

**Comment by mritd** [comment]
如果在 base 镜像里加入一些 jvm 参数可能导致后面的无法强行覆盖，所以目前我们将 jvm 参数放到了最后的业务镜像里，等会我把以前的 jvm 参数写到文档里吧

**Comment by mritd** [comment]
@zhangguanzhang 已经更新了说明文档

**Comment by zhangguanzhang** [comment]
ok
