### ISSUE TITLE
语言设置问题

### ISSUE THREAD

**Issue by basefas** [Gozap/dockerfile#4]
您好，看了下您写的 dockerfile，其中有的会设置语言相关，有的则没有（下面几个参数）

```
ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV LANGUAGE en_US:en
```

请问什么情况下需要设置，是为了解决或避免什么问题？

**Comment by mritd** [comment]
这几个变量一般在 jdk 相关的镜像里都会增加，为了解决某些情况下的乱码问题，关于这些变量的含义你可以参考 [Arch 文档](https://wiki.archlinux.org/index.php/Locale_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87))。

**Comment by basefas** [comment]
学习了，感谢。
